name: Remove Old Files

on:
  push:
    branches:
      - main

jobs:
  remove_old_files:
    name: Remove old files
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Git
      run: sudo apt-get install git -y
      
    - name: Set up Git credentials
      run: |
        git config --global user.email "${{ github.event.pusher.email }}"
        git config --global user.name "${{ github.event.pusher.name }}"
        
    - name: List all folders
      run: |
        find . -type d > folders.txt
        
    - name: Find last commit in each folder
      run: |
        while IFS= read -r folder; do
          if [ -d "$folder" ]; then
            last_commit=$(cat "${folder}/last_commit.txt" 2>/dev/null || echo "${GITHUB_SHA}^")
            echo "$last_commit" > "${folder}/last_commit.txt"
          else
            echo "Folder $folder does not exist."
          fi
        done < folders.txt
      
    - name: Remove old files in modified folders
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: |
        while IFS= read -r folder; do
          if [ -d "$folder" ]; then
            last_commit=$(cat "${folder}/last_commit.txt" 2>/dev/null || echo "${GITHUB_SHA}^")
            git diff --name-only "$last_commit" "$GITHUB_SHA" -- "$folder" > "${folder}/modified_files.txt"
            while IFS= read -r file; do
              rm -f "$folder/$file"
            done < "${folder}/modified_files.txt"
          else
            echo "Folder $folder does not exist."
          fi
        done < folders.txt
        
    - name: Commit changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Remove old files"
        
    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.RV_TOKEN }}
