name: Main Commit Check

on:
  push:
    branches:
      - main

jobs:
  check-files:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: RahulNative/Forge-cli
          ssh-strict: true
          persist-credentials: false
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true
          token: ${{ secrets.RV_TOKEN }}

      - name: Set up Git
        run: | 
          git config --global credential.helper '!f() { sleep 1; echo "username=token"; echo "password=${{ secrets.RV_TOKEN }}"; }; f'
      - name: Find and remove old files
        run: |
          # Change to the directory where your folders are located
          cd $GITHUB_WORKSPACE

          for item in *; do
              # Check if the item is a directory
              if [ -d "$item" ]; then
                  for subitem in "$item"/*; do
                      if [ -d "$subitem" ]; then
                          cd "$subitem"
                          file_count=$(ls -1 | wc -l)
                          # If there are more than 2 files, remove the oldest ones
                          if [ $file_count -gt 2 ]; then
                            ls -t | head -n 1 | tac  | xargs -I {} rm -f {}
                          fi
                          cd $GITHUB_WORKSPACE
                      fi
                  done
              fi
          done

      - name: Check for changes and commit
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.email "${{ github.event.pusher.email }}"
            git config user.name "${{ github.event.pusher.name }}"
            git add .
            git commit -m "Remove older files [skip ci]"
            # Use the PAT for authentication
            git push https://github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
