name: Remove Old Files

on:
  push:
    branches:
      - main

jobs:
  remove_old_files:
    name: Remove old files
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Git
      run: sudo apt-get install git -y
      
    - name: Set up Git credentials
      run: |
        git config --global user.email "${{ github.event.pusher.email }}"
        git config --global user.name "${{ github.event.pusher.name }}"
      
    - name: List all folders
      run: |
        find . -type d > folders.txt
        
    - name: Remove old files except last three inserted
      run: |
        while IFS= read -r folder; do
          cd "$folder" || continue
          # Remove files only, not directories
          find . -maxdepth 1 -type f -printf "%T@\t%p\0" | sort -z -n | head -z -n -3 | cut -z -f2- | xargs -0 rm -f
          cd ..
        done < folders.txt

        
    - name: Commit changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Remove old files"
        
    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.RV_TOKEN }}
