name: Main Commit Check

on:
  push:
    branches:
      - main

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: RahulNative/Forge-cli
          ssh-strict: true
          persist-credentials: false
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true
          token: ${{ secrets.RV_TOKEN }}

      - name: Set up Git
        run: | 
          git config --global credential.helper '!f() { sleep 1; echo "username=token"; echo "password=${{ secrets.RV_TOKEN }}"; }; f'

      - name: Find and remove old files
        run: |
          # Change to the directory where your folders are located
          cd $GITHUB_WORKSPACE
          # Define the string
          a=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})

          # Split the string by '/' and get the second last element
          folder_name=$(echo $a | rev | cut -d'/' -f 2 | rev)
          
          # List all files and directories except for .git
          for item in *; do
            # Check if the item is a directory
            if [ -d "$item" ]; then
              # Change to the folder
              cd "$item"
              # Count the number of files in the folders
              file_count=$(ls -1 | wc -l)
              # If there are more than 2 files, remove the oldest ones
              if [ $file_count -gt 2 ]; then
                ls -t | tail -n +3 | xargs -I {} rm -f {}
              fi
              # Move back to the main directory
              cd ..
            fi
          done
          
      - name: Check for changes and commit
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.email "${{ github.event.pusher.email }}"
            git config user.name "${{ github.event.pusher.name }}"
            git add .
            git commit -m "Remove older files"
            # Use the PAT for authentication
            git push https://github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
