name: Main Commit Check

on:
  push:
    branches:
      - main

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: RahulNative/Forge-cli
          ssh-strict: true
          persist-credentials: false
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true
          token: ${{ secrets.RV_TOKEN }}

      - name: Set up Git
        run: | 
          git config --global credential.helper '!f() { sleep 1; echo "username=token"; echo "password=${{ secrets.RV_TOKEN }}"; }; f'

      - name: Determine updated folder
        id: determine_folder
        run: |
          # Determine the folder containing the modified file
          modified_file=$(git diff --name-only HEAD^ HEAD)
          folder=$(dirname "$modified_file")
          echo "FOLDER=$folder" >> $GITHUB_ENV

      - name: Remove old files
        run: |
          folder="$FOLDER"
          # Change to the directory of the updated folder
          cd "$GITHUB_WORKSPACE/$folder" || exit
          # List all files in the folder
          files=(*)
          # If there are more than 2 files, sort them by modification time and remove the oldest ones
          if [ ${#files[@]} -gt 2 ]; then
            # Sort files by modification time in ascending order
            sorted_files=($(ls -t --time=atime))
            # Remove the oldest files except the three most recent ones
            for ((i=2; i<${#sorted_files[@]}; i++)); do
              rm -f "${sorted_files[$i]}"
            done
          fi

      - name: Check for changes and commit
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.email "${{ github.event.pusher.email }}"
            git config user.name "${{ github.event.pusher.name }}"
            git add .
            git commit -m "Remove older files"
            # Use the PAT for authentication
            git push https://github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
