name: Delete First Inserted File

on:
  push:
    branches:
      - check  # Replace with the actual branch name

jobs:
  delete-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Identify first inserted file
        id: identify-file
        run: |
          first_file=$(git diff --name-only HEAD^ HEAD | head -1)
          echo "first_file=$first_file" >> $GITHUB_OUTPUT

      - name: Delete file
        if: steps.identify-file.outputs.first_file
        run: |
          rm ${{ steps.identify-file.outputs.first_file }}
          git commit -a -m "Deleted first inserted file: ${{ steps.identify-file.outputs.first_file }}"
          git push
